name: CI - Angular

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: FrontComponent/package-lock.json

      - name: Instalar dependencias
        working-directory: FrontComponent
        run: npm ci


      - name: Compilar proyecto
        run: npm run build

      - name: Ejecutar pruebas
        run: npm test -- --watch=false --browsers=ChromeHeadless